#!/usr/bin/env bash
# This script transfers a file from our client to a server
#
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check if the number of arguments is correct
if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp "$FILE" "$USERNAME"@"$IP":~/
