#!/usr/bin/env bash
# This script transfers a file from our client to a server
#
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check if the number of arguments is correct
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

if [ -n "$SSH_KEY" ]; then
	scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
else
	scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
fi
