#!/usr/bin/env bash
# Configure the nginx server to redirect all requests from /redirect_me to another page.
#
# Requirements:
# - The redirection must be a “301 Moved Permanently”
# - You answer file should be a Bash script containing commands to automatically configure a Ubuntu machine to respect above requirements
# - Using what you did with 1-install_nginx_web_server, write 3-redirection so that it configures a brand new Ubuntu machine to the requirements asked in this task

# Install nginx
apt-get update
apt-get install -y nginx

# Make sure nginx is running
service nginx start

# Make sure nginx starts on boot
update-rc.d nginx defaults

# Create the file /etc/nginx/sites-available/default
touch /etc/nginx/sites-available/default

# Edit the file /etc/nginx/sites-available/default
# Add a rewrite rule inside the server block
sed -i 's/index index.html index.htm index.nginx-debian.html;/index index.html index.htm index.nginx-debian.html;\nrewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/' /etc/nginx/sites-available/default

# Reload nginx server
service nginx reload
