#!/usr/bin/env bash
# This script prints "Best School" 10 times, but for the 9th iteration, displays "Best School" and then "Hi" on a new line

count=1
while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	((count++))
done
