#!/usr/bin/env bash
# Prints iterates 10 times, on the 4th iteration, print "bad luck",
# on the 8th iteration print "good luck".
# Print "Best School" for other iterations

count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
