#!/usr/bin/env bash
# displays number from 1 to 20
# displays 4 and then "bad luck from China"
# displays 9 and then "bad luck from Japan"
# displays 17 and then "bad luck from Italy"

number=1
while [ $number -le 20 ]
do
	echo "$number"
	case $number in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((number++))
done
