#!/usr/bin/env bash
# provides information about the school file
# if the file exists, print "school file exists"
# if the file doesn't exist "school file does not exist"
# if the file is empty "school file is empty"
# if the file is not empty "school file is not empty"
# if the file is a regular file "school is a regular file"
# if the file is not regular file do nothing

file="school"
if [[ -e "$file" ]]
then
	echo "$file file exists"
	if [[ -s "$file" ]]
	then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [[ -f "$file" ]]
	then
		echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi

